//
//  Random.swift
//  Party Explorer
//
//  Created by Marius Genton on 11/30/23.
//

import Foundation

class Random {
    
    // Generated by Chat-GPT
    private static let partyNames = [
        "Celestial Soiree",
        "Midnight Masquerade",
        "Disco Inferno Bash",
        "Groove Gala",
        "Enchanted Euphoria",
        "Neon Nights Fiesta",
        "Electric Extravaganza",
        "Glitter Glam Gathering",
        "Tropical Twilight Party",
        "Starry Skies Shindig",
        "Carnival of Colors",
        "Wonderland Whirlwind",
        "Retro Rendezvous",
        "Bohemian Bliss Bash",
        "Sapphire Serenade",
        "Mardi Gras Madness",
        "Galactic Groove Gathering",
        "Emerald Eden Event",
        "Salsa Sensation Soiree",
        "Whimsical Winter Wonderland",
        "Mystic Moonlight Mixer",
        "Jazz Jubilee Jam",
        "Radiant Rainbow Revelry",
        "Velvet Vortex Voyage",
        "Cosmic Carnival",
        "Fire and Ice Fiesta",
        "En Vogue Extravaganza",
        "Secret Garden Soiree",
        "Funky Fusion Fest",
        "Crystal Cascade Celebration",
        "Jazzed-Up Jamboree",
        "Luminous Lagoon Luau",
        "Electric Dreams Eruption",
        "Posh Paradise Party",
        "Carnival Carousel Cabaret",
        "Bollywood Bliss Bash",
        "Twilight Tango Tease",
        "Razzle Dazzle Riot",
        "Golden Gala Gaiety",
        "Skyline Serenity Soiree",
        "Wonderland Wonderscape",
        "Ecliptic Eclipse Extravaganza",
        "Disco Diva Delight",
        "Ruby Red Revelry",
        "Psychedelic Symphony",
        "Enchanted Evening Ensemble",
        "Jazz Age Jollification",
        "Groovy Garden Gala",
        "Blue Moon Ball",
        "Sizzling Summer Soiree",
        "Neon Nectar Nook",
        "Neon Noir Nuptials",
        "Moonlit Mischief Mixer",
        "Disco Dip Dance-off",
        "Enchanted Epoch Event",
        "Cosmic Carnival Celebration",
        "Radiant Rendezvous Revue",
        "Neon Nights Nirvana",
        "Serendipity Soiree",
        "Mystical Mingle Mixer",
        "Jazzy Jungle Jamboree",
        "Sapphire Serenade Soiree",
        "Disco Dream Delight",
        "Ethereal Elegance Extravaganza",
        "Luminous Lagoon Luau",
        "Glitter Grotto Gala",
        "Galactic Gala Gaiety",
        "Radiant Rhythm Revelry",
        "Enchanté Evening Ensemble",
        "Moonlit Masquerade Mingle",
        "Whirlwind Wonderland Whimsy",
        "Eclectic Epoch Extravaganza",
        "Radiant Retro Rendezvous",
        "Neon Nectar Nuptials",
        "Celestial Circus Celebration",
        "Bohemian Bliss Bash",
        "Groovy Garden Gathering",
        "Electric Dreams Eruption",
        "Velvet Vortex Voyage",
        "Cosmic Cabaret Carnival",
        "Jazzed-Up Jubilation"
    ]
    
    static func partyName() -> String {
        return self.partyNames.randomElement()! // Force-unwrap is safe here, as we know array is not empty
    }
    
    static func partyBannerImage() -> String {
        return String(Int.random(in: 1...12))
    }
    
    static func partyPrice() -> Double {
        return Double(Int.random(in: 10...30) / 2) // Random integers divided by two to simulate real-world data (highly unlikely that prices will contain arbitrary decimals, lowest precision is typically 50 cents)
    }
    
    static func partyStartDate() -> Date {
        
        // We constrain the start date to [3 days ago, in 1 week].
        let lowerBoundFromNow = -3 * 24 * 3600
        let upperBoundFromNow = 7 * 24 * 3600
        
        
        return Date().addingTimeInterval(TimeInterval(Int.random(in: lowerBoundFromNow...upperBoundFromNow)))
    }
    
    static func partyEndDate(_ start: Date) -> Date? {
        if Int.random(in: 0...100) > 50 { return nil }
        let duration = Int.random(in: 2...6) * 3600 // Make parties last 2-6 hours
        
        return start.addingTimeInterval(TimeInterval(duration))
    }

}
